#! /usr/bin/env bash

BASEPATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )"/.. && pwd )"

for PACKAGE in ${BASEPATH}/packages/*; do
    SHOULD_LOAD=1
    if [ -f $PACKAGE/should_load.sh ]; then
        sh $PACKAGE/should_load.sh
        [ $? -ne 0 ] && SHOULD_LOAD=0
    fi
    [ $SHOULD_LOAD == 0 ] && continue
    if [[ $@ == *-p* ]]; then
        echo ${PACKAGE}
    else
        basename ${PACKAGE}
    fi
done
